export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const LOGGEDIN = "LOGGEDIN";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";


export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const RETRIEVE_PRODUCTS = "RETRIEVE_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const ADD_TO_CART = "ADD_TO_CART";
export const RETRIEVE_CART = "RETRIEVE_CART";
export const UPDATE_CART = "UPDATE_CART";
export const DELETE_CART = "DELETE_CART";

export const ADD_ADDRESS = "ADD_ADDRESS";
export const RETRIEVE_ADDRESS = "RETRIEVE_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const RETRIEVE_WISHLIST = "RETRIEVE_WISHLIST";
export const DELETE_WISHLIST = "DELETE_WISHLIST";

export const CREATE_ORDER = "CREATE_ORDER";
export const RETRIEVE_ORDERS = "RETRIEVE_ORDERS";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
